In [1]:
# -*- coding: utf-8 -*-
"""



"""

# U2A1. PROBLEMARIO - Operaciones matriciales y vectoriales
# Importación de librerías necesarias
import numpy as np
import matplotlib.pyplot as plt

print("=== U2A1 - OPERACIONES MATRICIALES Y VECTORIALES ===\n")

=== U2A1 - OPERACIONES MATRICIALES Y VECTORIALES ===



In [2]:
# EJERCICIO 1: Suma de matrices
print("--- EJERCICIO 1: SUMA DE MATRICES ---")

# Definir matrices A y B
A = np.array([[2, 4, 6], [1, 3, 5], [7, 9, 11]])
B = np.array([[12, 10, 8], [6, 4, 2], [0, -2, -4]])

# Realizar suma
C = A + B

print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)
print("\nMatriz resultante C = A + B:")
print(C)

--- EJERCICIO 1: SUMA DE MATRICES ---
Matriz A:
[[ 2  4  6]
 [ 1  3  5]
 [ 7  9 11]]

Matriz B:
[[12 10  8]
 [ 6  4  2]
 [ 0 -2 -4]]

Matriz resultante C = A + B:
[[14 14 14]
 [ 7  7  7]
 [ 7  7  7]]


In [3]:
# EJERCICIO 2: Multiplicación de matrices
print("\n--- EJERCICIO 2: MULTIPLICACIÓN DE MATRICES ---")

# Definir matrices A y B
A = np.array([[2, 1], [3, 4], [5, 6]])
B = np.array([[7, 8], [9, 10]])

# Realizar multiplicación
C = np.dot(A, B)

print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)
print("\nMatriz resultante C = A * B:")
print(C)


--- EJERCICIO 2: MULTIPLICACIÓN DE MATRICES ---
Matriz A:
[[2 1]
 [3 4]
 [5 6]]

Matriz B:
[[ 7  8]
 [ 9 10]]

Matriz resultante C = A * B:
[[ 23  26]
 [ 57  64]
 [ 89 100]]


In [4]:
# EJERCICIO 3: Inversión de matriz
print("\n--- EJERCICIO 3: INVERSIÓN DE MATRIZ ---")

# Definir matriz A
A = np.array([[4, 7, 2], [2, 6, 8], [3, 1, 9]])

# Calcular inversa
try:
    A_inv = np.linalg.inv(A)
    print("Matriz A:")
    print(A)
    print("\nMatriz inversa A^(-1):")
    print(A_inv)

    # Verificar que A * A_inv = I (matriz identidad)
    identidad = np.dot(A, A_inv)
    print("\nVerificación (A * A_inv ≈ I):")
    print(identidad)
except np.linalg.LinAlgError:
    print("La matriz no es invertible")


--- EJERCICIO 3: INVERSIÓN DE MATRIZ ---
Matriz A:
[[4 7 2]
 [2 6 8]
 [3 1 9]]

Matriz inversa A^(-1):
[[ 0.2371134  -0.31443299  0.22680412]
 [ 0.03092784  0.15463918 -0.1443299 ]
 [-0.08247423  0.08762887  0.05154639]]

Verificación (A * A_inv ≈ I):
[[ 1.00000000e+00 -1.66533454e-16  1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 1.52655666e-16 -2.49800181e-16  1.00000000e+00]]


In [5]:
# EJERCICIO 4: Resolución de sistema de ecuaciones lineales
print("\n--- EJERCICIO 4: SISTEMA DE ECUACIONES LINEALES ---")

# Sistema: 2x + y + z = 8
#          3x + 5y + 2z = 21
#          x + 2y + 4z = 11

# Matriz de coeficientes
A = np.array([[2, 1, 1],
              [3, 5, 2],
              [1, 2, 4]])

# Vector de términos constantes
B = np.array([8, 21, 11])

# Resolver sistema
X = np.linalg.solve(A, B)

print("Matriz de coeficientes A:")
print(A)
print("\nVector de términos constantes B:")
print(B)
print("\nSolución X = [x, y, z]:")
print(f"x = {X[0]:.2f}, y = {X[1]:.2f}, z = {X[2]:.2f}")

# Verificación
verificacion = np.dot(A, X)
print("\nVerificación (A * X = B):")
print(f"Calculado: {verificacion}")
print(f"Esperado:  {B}")


--- EJERCICIO 4: SISTEMA DE ECUACIONES LINEALES ---
Matriz de coeficientes A:
[[2 1 1]
 [3 5 2]
 [1 2 4]]

Vector de términos constantes B:
[ 8 21 11]

Solución X = [x, y, z]:
x = 2.30, y = 2.43, z = 0.96

Verificación (A * X = B):
Calculado: [ 8. 21. 11.]
Esperado:  [ 8 21 11]


In [6]:
# EJERCICIO 5: Cálculo de determinante
print("\n--- EJERCICIO 5: CÁLCULO DE DETERMINANTE ---")

# Definir matriz A
A = np.array([[3, -2, 1],
              [0, 5, 4],
              [2, 1, 7]])

# Calcular determinante
det_A = np.linalg.det(A)

print("Matriz A:")
print(A)
print(f"\nDeterminante de A: {det_A:.2f}")


--- EJERCICIO 5: CÁLCULO DE DETERMINANTE ---
Matriz A:
[[ 3 -2  1]
 [ 0  5  4]
 [ 2  1  7]]

Determinante de A: 67.00


In [7]:
# EJERCICIO 6: Producto cruz de vectores
print("\n--- EJERCICIO 6: PRODUCTO CRUZ DE VECTORES ---")

# Definir vectores A y B
A = np.array([2, 3, -1])
B = np.array([1, -2, 4])

# Calcular producto cruz
cross_product = np.cross(A, B)

print(f"Vector A: {A}")
print(f"Vector B: {B}")
print(f"Producto cruz A x B: {cross_product}")

# Verificación de ortogonalidad
dot_AC = np.dot(A, cross_product)
dot_BC = np.dot(B, cross_product)
print(f"\nVerificación de ortogonalidad:")
print(f"A · (A x B) = {dot_AC} (debe ser 0)")
print(f"B · (A x B) = {dot_BC} (debe ser 0)")


--- EJERCICIO 6: PRODUCTO CRUZ DE VECTORES ---
Vector A: [ 2  3 -1]
Vector B: [ 1 -2  4]
Producto cruz A x B: [10 -9 -7]

Verificación de ortogonalidad:
A · (A x B) = 0 (debe ser 0)
B · (A x B) = 0 (debe ser 0)


In [8]:
# EJERCICIO 7: Proyección ortogonal
print("\n--- EJERCICIO 7: PROYECCIÓN ORTOGONAL ---")

# Definir vectores V y U
V = np.array([5, -3, 2])
U = np.array([2, 1, 2])

# Calcular proyección ortogonal de V sobre U
proj_V_on_U = (np.dot(V, U) / np.dot(U, U)) * U

print(f"Vector V: {V}")
print(f"Vector U: {U}")
print(f"Proyección ortogonal de V sobre U: {proj_V_on_U}")

# Verificación
componente_ortogonal = V - proj_V_on_U
dot_verification = np.dot(componente_ortogonal, U)
print(f"\nVerificación (componente ortogonal · U): {dot_verification} (debe ser 0)")


--- EJERCICIO 7: PROYECCIÓN ORTOGONAL ---
Vector V: [ 5 -3  2]
Vector U: [2 1 2]
Proyección ortogonal de V sobre U: [2.44444444 1.22222222 2.44444444]

Verificación (componente ortogonal · U): -8.881784197001252e-16 (debe ser 0)


In [9]:
# EJERCICIO 8: Producto escalar de proyecciones
print("\n--- EJERCICIO 8: PRODUCTO ESCALAR DE PROYECCIONES ---")

# Definir vectores
V = np.array([3, -1, 2])
U = np.array([2, 2, -1])
W = np.array([1, 4, -2])

# Calcular proyecciones
proj_V_on_U = (np.dot(V, U) / np.dot(U, U)) * U
proj_V_on_W = (np.dot(V, W) / np.dot(W, W)) * W

# Calcular producto escalar
dot_product = np.dot(proj_V_on_U, proj_V_on_W)

print(f"Vector V: {V}")
print(f"Vector U: {U}")
print(f"Vector W: {W}")
print(f"\nProyección de V sobre U: {proj_V_on_U}")
print(f"Proyección de V sobre W: {proj_V_on_W}")
print(f"\nProducto escalar de las proyecciones: {dot_product:.2f}")


--- EJERCICIO 8: PRODUCTO ESCALAR DE PROYECCIONES ---
Vector V: [ 3 -1  2]
Vector U: [ 2  2 -1]
Vector W: [ 1  4 -2]

Proyección de V sobre U: [ 0.44444444  0.44444444 -0.22222222]
Proyección de V sobre W: [-0.23809524 -0.95238095  0.47619048]

Producto escalar de las proyecciones: -0.63


In [10]:
# EJERCICIO 9: Ortogonalización de Gram-Schmidt
print("\n--- EJERCICIO 9: ORTOGONALIZACIÓN DE GRAM-SCHMIDT ---")

# Definir vectores originales
v1 = np.array([1, 1, 0])
v2 = np.array([1, 2, 1])
v3 = np.array([2, 1, 3])

print("Vectores originales:")
print(f"v1 = {v1}")
print(f"v2 = {v2}")
print(f"v3 = {v3}")

# Proceso de Gram-Schmidt
u1 = v1.copy()

u2 = v2 - (np.dot(v2, u1) / np.dot(u1, u1)) * u1

u3 = v3 - (np.dot(v3, u1) / np.dot(u1, u1)) * u1 - (np.dot(v3, u2) / np.dot(u2, u2)) * u2

print("\nVectores ortogonalizados:")
print(f"u1 = {u1}")
print(f"u2 = {u2}")
print(f"u3 = {u3}")

# Verificación de ortogonalidad
print("\nVerificación de ortogonalidad:")
print(f"u1 · u2 = {np.dot(u1, u2)}")
print(f"u1 · u3 = {np.dot(u1, u3)}")
print(f"u2 · u3 = {np.dot(u2, u3)}")


--- EJERCICIO 9: ORTOGONALIZACIÓN DE GRAM-SCHMIDT ---
Vectores originales:
v1 = [1 1 0]
v2 = [1 2 1]
v3 = [2 1 3]

Vectores ortogonalizados:
u1 = [1 1 0]
u2 = [-0.5  0.5  1. ]
u3 = [ 1.33333333 -1.33333333  1.33333333]

Verificación de ortogonalidad:
u1 · u2 = 0.0
u1 · u3 = 0.0
u2 · u3 = -2.220446049250313e-16


In [11]:
# EJERCICIO 10: Espacio nulo
print("\n--- EJERCICIO 10: ESPACIO NULO ---")

# Definir matriz A
A = np.array([[1, 2, 0, 3],
              [0, 1, 0, 2],
              [0, 0, 1, 1]])

print("Matriz A:")
print(A)

# Encontrar el espacio nulo manualmente
# Resolvemos Ax = 0
# x1 + 2x2 + 3x4 = 0
# x2 + 2x4 = 0
# x3 + x4 = 0

# Variable libre: x4 = t
# Entonces:
# x2 = -2t
# x3 = -t
# x1 = -2(-2t) - 3t = 4t - 3t = t

# Vector base del espacio nulo: [1, -2, -1, 1]^T

base_nulo = np.array([1, -2, -1, 1])

print(f"\nBase del espacio nulo:")
print(base_nulo)

# Verificación
verificacion = np.dot(A, base_nulo)
print(f"\nVerificación (A * base_nulo): {verificacion} (debe ser [0, 0, 0])")


--- EJERCICIO 10: ESPACIO NULO ---
Matriz A:
[[1 2 0 3]
 [0 1 0 2]
 [0 0 1 1]]

Base del espacio nulo:
[ 1 -2 -1  1]

Verificación (A * base_nulo): [0 0 0] (debe ser [0, 0, 0])
